import type { ServerBuild } from '@remix-run/cloudflare';
import { createPagesFunctionHandler } from '@remix-run/cloudflare-pages';

// @ts-ignore because the server build file is generated by `remix vite:build`
import * as serverBuild from '../build/server';

const handler = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
  mode: 'production',
});

export const onRequest: PagesFunction<Env> = async (context) => {
  const response = await handler(context);

  // Critical: Enable cross-origin isolation for SharedArrayBuffer (required by WebContainers)
  response.headers.set('Cross-Origin-Embedder-Policy', 'require-corp');
  response.headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  response.headers.set('Cross-Origin-Resource-Policy', 'cross-origin');

  // Ensure CORS is permissive for WebContainer worker scripts
  if (!response.headers.has('Access-Control-Allow-Origin')) {
    response.headers.set('Access-Control-Allow-Origin', '*');
  }

  return response;
};